#!/usr/bin/env python3
"""Generate the Markdown pages that have a data source: the cover (01), the five
signal pages (06–10) and the closing page (17), plus guide/README.md (contents).

    python3 src/render/build_pages.py

Pages 02–05 and 11–16 are written by hand in guide/ and are left untouched.
"""
from __future__ import annotations

import sys

from common import GUIDE, ROOT, list_pages, load_meta, load_signals, parse_page

HEADER = "<sub>{title} · {subtitle} · page {n} of {total}</sub>\n\n"
GENERATED = "<!-- Generated by src/render/build_pages.py from {src}. Edit the source, then run `make pages`. -->\n"

SIGNAL_PAGES = {
    "06": {"ids": ["01", "02"], "slug": "signals-api-health-and-liveness", "title": "API health · Control-plane liveness",
           "lead": "Is the platform responding, and is the capacity it reports real?"},
    "07": {"ids": ["03", "04"], "slug": "signals-messaging-and-database", "title": "Messaging health · Database health",
           "lead": "The two shared dependencies every operation relies on."},
    "08": {"ids": ["05", "06"], "slug": "signals-scheduling-and-capacity", "title": "Scheduling and build outcomes · Capacity headroom",
           "lead": "Capacity problem, or health problem?"},
    "09": {"ids": ["07", "08"], "slug": "signals-storage-and-network", "title": "Storage health and latency · Network data path and agents",
           "lead": "The layers with the widest blast radius."},
    "10": {"ids": ["09", "10"], "slug": "signals-state-integrity-and-reliability", "title": "Workload state integrity · Reliability trend",
           "lead": "Is what the platform reports true? Are we stabilising, or drifting?"},
}


def nav(prev: tuple[str, str] | None, nxt: tuple[str, str] | None) -> str:
    parts = []
    if prev:
        parts.append(f"[← {prev[0]}]({prev[1]})")
    parts.append("[Contents](README.md#contents)")
    if nxt:
        parts.append(f"[{nxt[0]} →]({nxt[1]})")
    return "\n---\n\n" + " &nbsp;·&nbsp; ".join(parts) + "\n"


def page_index(meta) -> list[dict]:
    """The seventeen pages in order: number, slug, title (from md when it exists)."""
    idx = {}
    for p in list_pages():
        pg = parse_page(p)
        idx[pg["number"]] = {"number": pg["number"], "slug": pg["slug"], "title": pg["title"], "file": p.name, "figure": pg["figure"]}
    idx["01"] = {"number": "01", "slug": "regaining-control", "title": meta["title"], "file": "01-regaining-control.md", "figure": "01-regaining-control"}
    for n, sp in SIGNAL_PAGES.items():
        idx[n] = {"number": n, "slug": sp["slug"], "title": f"Signals {sp['ids'][0]}–{sp['ids'][1]} · {sp['title']}", "file": f"{n}-{sp['slug']}.md", "figure": ""}
    idx["17"] = {"number": "17", "slug": "lets-talk", "title": meta["closing"]["title"], "file": "17-lets-talk.md", "figure": ""}
    return [idx[f"{i:02d}"] for i in range(1, meta["pages"] + 1)]


def write_cover(meta, pages):
    n = "01"
    out = HEADER.format(title=meta["title"], subtitle=meta["subtitle"], n=n, total=meta["pages"])
    out += GENERATED.format(src="src/content/meta.yaml")
    out += f"\n# 01 · {meta['title']}\n\n*{meta['subtitle']}*\n\n"
    out += f"**{meta['tagline']} {meta['audience_line']}**\n\n"
    out += f"![{meta['title']} — {meta['subtitle']}: the ten signals converging into understanding, then decision, and the seven-step path](../figures/01-regaining-control.png)\n\n"
    out += f"### What this guide is\n\n{meta['pages']} pages, one idea and one figure per page, {meta['reading_time'].replace('to read', 'to read the essentials')}. It is written for the people who decide what happens to a platform, not for the people who operate it, and it stays technically exact so that both can read it together.\n\n"
    out += "### The path\n\n`" + " → ".join(meta["journey"]) + "`\n\n"
    out += f"### The message\n\n> {meta['central_message']}\n>\n> {meta['opening_message']}\n\n"
    out += f"**{meta['author']['name']}** — {meta['author']['line']} [LinkedIn]({meta['author']['linkedin']}) · [GitHub]({meta['author']['github']})\n"
    out += nav(None, (f"{pages[1]['number']} · {pages[1]['title']}", pages[1]["file"]))
    (GUIDE / "01-regaining-control.md").write_text(out, encoding="utf-8")


def signal_md(s: dict) -> str:
    steps = " · ".join(f"**{st.capitalize()}**" if st == s["decision_context"]["typical"] else st.capitalize() for st in ["monitor", "investigate", "stabilise", "escalate"])
    o = f"### Signal {s['id']} · {s['name']}\n\n"
    o += f"*{s['subtitle']}* · {s['domain_label']}\n\n"
    o += f"<img src=\"../figures/cards/{s['id']}-{s['slug']}.png\" width=\"420\" alt=\"KPI card, signal {s['id']}: {s['name']}. {s['visual']['label']}.\">\n\n"
    o += f"**What we see.** {s['what_we_see']}\n\n"
    o += f"**Technical meaning.** {s['technical_meaning']}\n\n"
    o += f"**Why it matters.** {s['why_it_matters']['users']} {s['why_it_matters']['business']}\n\n"
    o += f"**If nothing is done.** {s['if_nothing_is_done']}\n\n"
    o += f"**Management question.** *{s['management_question']}*\n\n"
    o += f"**Decision context.** {steps} — {s['decision_context']['note']}\n\n"
    o += "**Read with.** " + " · ".join(s["read_with_names"]) + "\n\n"
    o += "**Sources.** " + " · ".join(f"[{src['title']}]({src['url']})" for src in s.get("sources", [])) + "\n\n"
    return o


def write_signal_pages(meta, signals, pages):
    by_id = {s["id"]: s for s in signals}
    for n, sp in SIGNAL_PAGES.items():
        i = int(n) - 1
        out = HEADER.format(title=meta["title"], subtitle=meta["subtitle"], n=n, total=meta["pages"])
        out += GENERATED.format(src="signals/*.yaml")
        out += f"\n# {n} · {sp['title']}\n\n*The signals · {sp['ids'][0]}–{sp['ids'][1]} / 10*\n\n**{sp['lead']}**\n\n"
        out += "Two signals per page, one card each: what we see, what it means, why it matters, what happens if nothing is done, the question a decision-maker can ask, and the decision it supports. The cards are generated from [`signals/`](../signals/); the selection criteria and the signals left out are in [`signals/README.md`](../signals/README.md).\n\n"
        for sid in sp["ids"]:
            out += signal_md(by_id[sid])
        prev = (f"{pages[i-1]['number']} · {pages[i-1]['title']}", pages[i-1]["file"])
        nxt = (f"{pages[i+1]['number']} · {pages[i+1]['title']}", pages[i+1]["file"])
        out += nav(prev, nxt)
        (GUIDE / f"{n}-{sp['slug']}.md").write_text(out, encoding="utf-8")


def write_closing(meta, pages):
    n = "17"
    c = meta["closing"]
    out = HEADER.format(title=meta["title"], subtitle=meta["subtitle"], n=n, total=meta["pages"])
    out += GENERATED.format(src="src/content/meta.yaml")
    out += f"\n# 17 · {c['title']}\n\n*{c['kicker']}*\n\n**{c['line']}**\n\n"
    for i, q in enumerate(c["questions"], 1):
        out += f"{i}. {q}\n"
    out += f"\n{c['invitation']}\n\n### Going further\n\n"
    for f in c["further"]:
        out += f"- **[{f['label']}]({f['url']})** — {f['text']}\n"
    out += f"\n### Author\n\n**{meta['author']['name']}** — {meta['author']['line']} [LinkedIn]({meta['author']['linkedin']}) · [GitHub]({meta['author']['github']})\n\n"
    out += f"### Licence\n\nVersion {meta['version']} · {meta['date']}. Licensed under [{meta['licence']['long']}]({meta['licence']['url']}) ({meta['licence']['short']}). {meta['licence']['notice']}\n"
    out += nav((f"{pages[15]['number']} · {pages[15]['title']}", pages[15]["file"]), None)
    (GUIDE / "17-lets-talk.md").write_text(out, encoding="utf-8")


def write_contents(meta, pages):
    out = f"# {meta['title']} — the guide, page by page\n\n"
    out += f"The {meta['pages']} pages of the PDF, one Markdown file each, readable here without opening the PDF. Each page carries one idea and one figure; the navigation at the bottom of every page leads to the next.\n\n"
    out += f"**Read it as a single document:** [`{ROOT.joinpath('Regaining-Control-Observability-for-OpenStack-Platforms-in-Difficulty.pdf').name}`](../Regaining-Control-Observability-for-OpenStack-Platforms-in-Difficulty.pdf) (A4, {meta['pages']} pages).\n\n"
    out += "**Five-minute path:** pages 02, 03, 05, 11, 13, 14 and 17. **Ten minutes:** everything except the signal cards. **Thirty minutes:** everything, then [`signals/`](../signals/) for the sources.\n\n"
    out += "## Contents\n\n| Page | Idea | Figure |\n|---|---|---|\n"
    for p in pages:
        fig = f"[fig. {p['number']}](../figures/{p['figure']}.png)" if p["figure"] else ("[cards](../figures/cards/)" if p["number"] in SIGNAL_PAGES else "—")
        out += f"| {p['number']} | [{p['title']}]({p['file']}) | {fig} |\n"
    out += "\n## How these pages are made\n\n"
    out += "Pages 02–05 and 11–16 are written by hand and are the source of the PDF text. Pages 06–10 are generated from the ten signal files in [`signals/`](../signals/), and pages 01 and 17 from [`src/content/meta.yaml`](../src/content/meta.yaml); a comment at the top of each generated page says so. The figures are rendered from [`src/figures/`](../src/figures/). See the [README](../README.md#how-it-is-built) for the build.\n"
    (GUIDE / "README.md").write_text(out, encoding="utf-8")


def main(argv):
    meta, signals = load_meta(), load_signals()
    pages = page_index(meta)
    write_cover(meta, pages)
    write_signal_pages(meta, signals, pages)
    write_closing(meta, pages)
    write_contents(meta, pages)
    print("  wrote guide/01, 06–10, 17 and guide/README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
